"""Captured-traffic replay harness for the OAuth flow (bead buiqr.9 (d)).

Replays the committed ``fixtures/claude_desktop_oauth_flow.json`` capture against
a Starlette ``TestClient`` (NO network). The capture is a discovery → authorize
→ token → refresh exchange.

SYNTHETIC FIXTURE — READ THIS
=============================
The fixture is SYNTHETIC, generated by driving the REAL ECM AS + MCP RS endpoints
(``fixtures/generate_oauth_flow_fixture.py``). There is no real Claude Desktop in
this environment and the Claude Desktop ``redirect_uri`` is still a placeholder
(bead buiqr.6). So the request/response SHAPES are real (emitted by the real
code), but the CLIENT side of the conversation is played by the generator, not a
real connector. ``test_fixture_is_marked_synthetic`` asserts the ``synthetic``
flag so a future REAL off-the-wire capture is a deliberate, reviewed change.

WHAT THIS HARNESS GUARDS
========================
The mcp-server CI job cannot import the backend AS (no fastapi/jose/slowapi), so
this harness cannot re-run the AS endpoints. Instead it:

  1. Asserts the captured discovery response matches what THIS RS emits today —
     so an AS/RS discovery-shape drift fails the replay (the discovery doc is the
     RS's own ``/.well-known/oauth-protected-resource`` output).
  2. Replays the captured ACCESS TOKEN (from the real /token response) against
     the RS ``/mcp`` endpoint and asserts it authenticates — proving a token the
     real AS minted is accepted by the RS offline verifier, end-to-end.
  3. Pins the captured AS token/refresh response SHAPES (RFC 6749 fields) so an
     AS contract change surfaces here as a deliberate fixture update.

Time handling: the captured access token has a real 15-min ``exp``. To keep the
replay deterministic forever (not a time-bomb), we freeze PyJWT's clock to a
point between the token's ``iat`` and ``exp`` while verifying — the token is
replayed exactly as captured, only the verifier's notion of "now" is pinned.
"""
import base64
import datetime as _dt
import json
from pathlib import Path

import jwt.api_jwt
from unittest.mock import patch

_FIXTURE_PATH = Path(__file__).resolve().parent / "fixtures" / "claude_desktop_oauth_flow.json"

_MCP_HEADERS = {
    "Content-Type": "application/json",
    "Accept": "application/json, text/event-stream",
}
_INITIALIZE = {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "initialize",
    "params": {
        "protocolVersion": "2025-06-18",
        "capabilities": {},
        "clientInfo": {"name": "test", "version": "0"},
    },
}


def _load_fixture() -> dict:
    return json.loads(_FIXTURE_PATH.read_text())


def _jwt_claims(token: str) -> dict:
    """Base64url-decode a JWT payload WITHOUT verifying (to read iat/exp/aud)."""
    payload = token.split(".")[1]
    payload += "=" * (-len(payload) % 4)
    return json.loads(base64.urlsafe_b64decode(payload))


def _frozen_now_datetime(epoch: int):
    """A datetime subclass whose .now() returns a fixed epoch (freezes PyJWT)."""

    class _Frozen(_dt.datetime):
        @classmethod
        def now(cls, tz=None):  # noqa: D401 — matches datetime.now signature
            return _dt.datetime.fromtimestamp(epoch, tz=tz)

    return _Frozen


def _parse_initialize_result(response):
    ctype = response.headers.get("content-type", "")
    body = response.text
    if "text/event-stream" in ctype:
        for line in body.splitlines():
            if line.startswith("data:"):
                return json.loads(line[len("data:"):].strip())
        raise AssertionError(f"no SSE data frame: {body!r}")
    return json.loads(body)


def _token_step(fixture: dict) -> dict:
    return next(s for s in fixture["flow"]["steps"] if s["name"] == "token")


def _refresh_step(fixture: dict) -> dict:
    return next(s for s in fixture["flow"]["steps"] if s["name"] == "refresh")


class TestCapturedFlowReplay:
    """Replay the synthetic capture against the RS (no network)."""

    def test_fixture_exists_and_is_marked_synthetic(self):
        """The capture is committed and explicitly flagged synthetic (buiqr.6 caveat)."""
        assert _FIXTURE_PATH.exists(), f"capture fixture missing at {_FIXTURE_PATH}"
        fixture = _load_fixture()
        assert fixture["synthetic"] is True, (
            "the committed capture must be flagged synthetic until a real Claude "
            "Desktop connector flow is captured (bead buiqr.6 redirect_uri)"
        )
        # The four flow stages are all present.
        names = [s["name"] for s in fixture["flow"]["steps"]]
        assert names == ["authorize", "approve", "token", "refresh"], names
        assert "discovery" in fixture["flow"]

    def test_captured_discovery_matches_this_rs(self, client):
        """The captured discovery doc equals what THIS RS serves today.

        Guards against AS/RS discovery-shape drift: if the RS discovery document
        changes shape, the committed capture no longer matches and this fails,
        forcing a deliberate re-capture.
        """
        fixture = _load_fixture()
        captured = fixture["flow"]["discovery"]["response"]["body"]
        issuer = fixture["signing"]["issuer"]
        resource = captured["resource"]
        with patch("server.resolve_issuer", return_value=issuer), \
             patch("server.get_oauth_allow_insecure", return_value=False), \
             patch("server.resolve_resource_url", return_value=resource):
            response = client.get("/.well-known/oauth-protected-resource")
        assert response.status_code == 200
        assert response.json() == captured

    def test_captured_token_response_has_rfc6749_shape(self):
        """The captured /token body carries the RFC 6749 success fields."""
        body = _token_step(_load_fixture())["response"]["body"]
        assert body["token_type"] == "Bearer"
        assert body["scope"] == "mcp"
        assert isinstance(body["expires_in"], int) and body["expires_in"] > 0
        assert body["access_token"] and body["refresh_token"]
        # The access token's claims match the RS contract (aud=ecm-mcp, scope=mcp).
        claims = _jwt_claims(body["access_token"])
        assert claims["aud"] == "ecm-mcp"
        assert claims["iss"] == _load_fixture()["signing"]["issuer"]
        assert "mcp" in claims["scope"].split()

    def test_captured_refresh_response_rotates_tokens(self):
        """The captured refresh step returns a NEW access + refresh pair (rotation)."""
        fixture = _load_fixture()
        token_body = _token_step(fixture)["response"]["body"]
        refresh_body = _refresh_step(fixture)["response"]["body"]
        assert refresh_body["token_type"] == "Bearer"
        # Rotation: the refresh response's tokens differ from the original grant's.
        assert refresh_body["access_token"] != token_body["access_token"]
        assert refresh_body["refresh_token"] != token_body["refresh_token"]

    def test_replay_captured_access_token_authenticates_rs(self, client):
        """The CAPTURED access token (real AS output) authenticates against the RS.

        This is the core replay assertion: a token minted by the real AS flow,
        presented as a Bearer to /mcp, drives a successful initialize on the
        OAuth path. We freeze PyJWT's clock between the token's iat and exp so the
        replay is deterministic regardless of when the suite runs, and patch the
        RS to verify against the fixture's pinned secret/issuer (the secret is a
        TEST value committed in the fixture for exactly this offline replay).
        """
        fixture = _load_fixture()
        signing = fixture["signing"]
        access_token = _token_step(fixture)["response"]["body"]["access_token"]
        claims = _jwt_claims(access_token)
        frozen_epoch = (claims["iat"] + claims["exp"]) // 2  # safely inside [iat, exp]

        with patch.object(jwt.api_jwt, "datetime", _frozen_now_datetime(frozen_epoch)), \
             patch("server.get_signing_key", return_value=signing["secret"]), \
             patch("server.get_oauth_issuer_for_rs", return_value=signing["issuer"]), \
             patch("server.get_mcp_api_key", return_value="unused-static-key-no-dots"):
            response = client.post(
                "/mcp",
                headers={**_MCP_HEADERS, "Authorization": f"Bearer {access_token}"},
                json=_INITIALIZE,
            )
        assert response.status_code == 200, response.text
        result = _parse_initialize_result(response)
        assert result["id"] == 1
        assert result["result"]["serverInfo"]["name"] == "ecm-mcp"

    def test_replay_rotated_access_token_also_authenticates(self, client):
        """The rotated access token from the refresh step also authenticates the RS.

        Confirms the full discovery→authorize→token→refresh capture is internally
        consistent: BOTH the original and the rotated access tokens verify offline.
        """
        fixture = _load_fixture()
        signing = fixture["signing"]
        rotated = _refresh_step(fixture)["response"]["body"]["access_token"]
        claims = _jwt_claims(rotated)
        frozen_epoch = (claims["iat"] + claims["exp"]) // 2

        with patch.object(jwt.api_jwt, "datetime", _frozen_now_datetime(frozen_epoch)), \
             patch("server.get_signing_key", return_value=signing["secret"]), \
             patch("server.get_oauth_issuer_for_rs", return_value=signing["issuer"]), \
             patch("server.get_mcp_api_key", return_value="unused-static-key-no-dots"):
            response = client.post(
                "/mcp",
                headers={**_MCP_HEADERS, "Authorization": f"Bearer {rotated}"},
                json=_INITIALIZE,
            )
        assert response.status_code == 200, response.text
