#!/usr/bin/env python3
"""Generate the SYNTHETIC Claude Desktop OAuth-flow capture (bead buiqr.9 (d)).

WHAT THIS PRODUCES
==================
``claude_desktop_oauth_flow.json`` — a discovery → authorize → token → refresh
exchange captured as request/response pairs, used by
``mcp-server/tests/test_oauth_flow_replay.py`` to replay the flow against a
TestClient (no network).

WHY IT IS SYNTHETIC (READ BEFORE TRUSTING THE FIXTURE)
======================================================
There is NO real Claude Desktop in this environment, and the Claude Desktop
``redirect_uri`` is still a TODO placeholder (bead buiqr.6 — see
``backend/auth/oauth_clients.py``). So this capture is NOT taken off the wire
from a real connector. Instead it is generated by DRIVING THE REAL ECM endpoints:

  - discovery: the REAL MCP RS handler (``mcp-server/server.py`` /
    ``oauth_discovery.py``) via a Starlette ``TestClient``.
  - authorize / approve / token / refresh: the REAL ECM AS endpoints
    (``backend/routers/oauth_mcp.py`` + ``backend/auth/oauth_provider.py``) via
    an httpx ASGI transport against the FastAPI app.

So every request/response SHAPE in the fixture is what the real code emits — no
hand-fabricated shapes. What is synthetic is the CLIENT side of the conversation
(we play the connector with the placeholder redirect_uri) and the deterministic
signing secret/issuer (pinned so the replay test can verify the captured access
token offline without the backend).

RE-CAPTURE TODO (buiqr.6 follow-up)
===================================
Once the real Claude Desktop Custom Connector redirect_uri is verified and a
real connector flow can be captured, RE-RUN this generator (or replace the
fixture with a real off-the-wire capture) so the replay test guards the real
client conversation, not this synthetic stand-in. The replay test asserts the
fixture's ``synthetic`` flag is True precisely so a future real capture is a
deliberate, reviewed change.

HOW TO RE-RUN
=============
    python mcp-server/tests/fixtures/generate_oauth_flow_fixture.py

The AS (``backend/``) and the RS (``mcp-server/``) BOTH ship a top-level
``config`` module, so they cannot be imported into one interpreter without a
namespace collision. This generator therefore captures each half in its OWN
subprocess (``--capture discovery`` / ``--capture as_flow``) and the parent
process stitches the two JSON results together. Requires the full dev env:
fastapi, python-jose, slowapi, starlette, pyjwt, httpx.
"""
from __future__ import annotations

import asyncio
import base64
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path
from urllib.parse import parse_qs, urlparse

# Deterministic signing material so the replay test can verify the captured
# access token offline. These are TEST values, never real secrets.
PINNED_SECRET = "synthetic-capture-signing-secret-32-bytes-padding-xx"
PINNED_ISSUER = "https://ecm.example.com"
RESOURCE_URL = "https://mcp.example.com"

FIXTURE_PATH = Path(__file__).resolve().parent / "claude_desktop_oauth_flow.json"
REPO_ROOT = Path(__file__).resolve().parents[3]
BACKEND_DIR = REPO_ROOT / "backend"
MCP_DIR = REPO_ROOT / "mcp-server"


def _pkce_pair() -> tuple[str, str]:
    verifier = "synthetic-connector-verifier-1234567890-abcdefghijklmnop"
    digest = hashlib.sha256(verifier.encode("ascii")).digest()
    challenge = base64.urlsafe_b64encode(digest).rstrip(b"=").decode("ascii")
    return verifier, challenge


def _capture_discovery() -> dict:
    """Drive the REAL MCP RS discovery handler and capture the response.

    Imported and run INSIDE a dedicated subprocess (cwd = mcp-server/) so the RS
    ``config`` module does not collide with the backend's ``config`` module.
    """
    from starlette.testclient import TestClient  # noqa: E402

    import server  # noqa: E402  (the real RS app — resolves to mcp-server/server.py)

    with TestClient(server.app) as client:
        resp = client.get(
            "/.well-known/oauth-protected-resource",
            headers={"host": "mcp.example.com"},
        )
    return {
        "request": {
            "method": "GET",
            "path": "/.well-known/oauth-protected-resource",
        },
        "response": {"status": resp.status_code, "body": resp.json()},
    }


async def _capture_as_flow() -> list[dict]:
    """Drive the REAL ECM AS endpoints and capture authorize/token/refresh.

    Imported and run INSIDE a dedicated subprocess (cwd = backend/) so the
    backend ``config`` module is the one that resolves.
    """
    import httpx  # noqa: E402
    from httpx import ASGITransport  # noqa: E402
    from sqlalchemy import create_engine  # noqa: E402
    from sqlalchemy.orm import sessionmaker  # noqa: E402
    from sqlalchemy.pool import StaticPool  # noqa: E402

    # Bring up an in-memory DB the same way backend/tests/conftest.py does, so the
    # AS endpoints (which open get_session() for the admin-session dependency) run
    # against a real-but-ephemeral database. Auth is disabled by default (open
    # mode), so RequireAdminIfEnabled binds the grant to the 'admin' sentinel.
    import database  # noqa: E402
    import models  # noqa: E402,F401 — registers tables with SQLAlchemy Base
    assert models

    engine = create_engine(
        "sqlite:///:memory:",
        connect_args={"check_same_thread": False},
        poolclass=StaticPool,
        echo=False,
    )
    database.Base.metadata.create_all(bind=engine)
    database._SessionLocal = sessionmaker(
        autocommit=False, autoflush=False, bind=engine, expire_on_commit=False
    )

    from auth.oauth_clients import (  # noqa: E402
        CLAUDE_DESKTOP_CLIENT_ID,
        seed_oauth_clients,
    )
    from auth.oauth_store import OAuthStore  # noqa: E402
    import auth.oauth_provider as provider_mod  # noqa: E402
    import routers.oauth_mcp as oauth_router  # noqa: E402
    from main import app  # noqa: E402  (the real FastAPI app)

    # An ephemeral seeded store + pinned signing secret, wired into the router.
    store = OAuthStore(Path("/tmp") / "synthetic_oauth_flow.db")
    store.init_schema()
    seed_oauth_clients(store)
    redirect_uri = store.get_client(CLAUDE_DESKTOP_CLIENT_ID)["redirect_uris"][0]

    oauth_router.get_oauth_store = lambda: store
    store.close = lambda: None  # the generator owns the lifecycle
    provider_mod._oauth_signing_secret = lambda: PINNED_SECRET

    verifier, challenge = _pkce_pair()
    steps: list[dict] = []

    transport = ASGITransport(app=app)
    async with httpx.AsyncClient(
        transport=transport, base_url="http://testserver"
    ) as client:
        # 1) authorize — binds the CSRF state, redirects to consent.
        authorize_params = {
            "response_type": "code",
            "client_id": CLAUDE_DESKTOP_CLIENT_ID,
            "redirect_uri": redirect_uri,
            "code_challenge": challenge,
            "code_challenge_method": "S256",
            "state": "synthetic-state-abc",
        }
        a = await client.get(
            "/api/oauth/authorize", params=authorize_params, follow_redirects=False
        )
        steps.append(
            {
                "name": "authorize",
                "request": {
                    "method": "GET",
                    "path": "/api/oauth/authorize",
                    "params": authorize_params,
                },
                "response": {
                    "status": a.status_code,
                    "location": a.headers.get("location"),
                },
            }
        )

        # 2) approve — mints the single-use code, redirects to the registered URI.
        approve_data = {
            "client_id": CLAUDE_DESKTOP_CLIENT_ID,
            "redirect_uri": redirect_uri,
            "code_challenge": challenge,
            "code_challenge_method": "S256",
            "state": "synthetic-state-abc",
        }
        ap = await client.post(
            "/api/oauth/authorize/approve", data=approve_data, follow_redirects=False
        )
        code = parse_qs(urlparse(ap.headers["location"]).query)["code"][0]
        steps.append(
            {
                "name": "approve",
                "request": {
                    "method": "POST",
                    "path": "/api/oauth/authorize/approve",
                    "data": approve_data,
                },
                "response": {
                    "status": ap.status_code,
                    "location": ap.headers.get("location"),
                },
            }
        )

        # 3) token — authorization_code grant → access + refresh tokens.
        token_data = {
            "grant_type": "authorization_code",
            "client_id": CLAUDE_DESKTOP_CLIENT_ID,
            "code": code,
            "redirect_uri": redirect_uri,
            "code_verifier": verifier,
        }
        t = await client.post("/api/oauth/token", data=token_data)
        token_body = t.json()
        steps.append(
            {
                "name": "token",
                "request": {
                    "method": "POST",
                    "path": "/api/oauth/token",
                    "data": token_data,
                },
                "response": {"status": t.status_code, "body": token_body},
            }
        )

        # 4) refresh — refresh_token grant → rotated access + refresh.
        refresh_data = {
            "grant_type": "refresh_token",
            "client_id": CLAUDE_DESKTOP_CLIENT_ID,
            "refresh_token": token_body["refresh_token"],
        }
        r = await client.post("/api/oauth/token", data=refresh_data)
        steps.append(
            {
                "name": "refresh",
                "request": {
                    "method": "POST",
                    "path": "/api/oauth/token",
                    "data": refresh_data,
                },
                "response": {"status": r.status_code, "body": r.json()},
            }
        )

    return steps


def _run_capture_subprocess(kind: str, cwd: Path) -> object:
    """Run one capture in a child interpreter (cwd set so the right ``config`` wins).

    The child prints a single JSON line on stdout prefixed with ``RESULT:``; we
    parse that. Running in a subprocess is what keeps the AS and RS ``config``
    modules from colliding in one interpreter.
    """
    env = dict(os.environ)
    env["OAUTH_ISSUER"] = PINNED_ISSUER
    env["MCP_RESOURCE_URL"] = RESOURCE_URL
    env["RATE_LIMIT_ENABLED"] = "0"
    proc = subprocess.run(
        [sys.executable, str(Path(__file__).resolve()), "--capture", kind],
        cwd=str(cwd),
        env=env,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"capture '{kind}' failed (exit {proc.returncode}):\n{proc.stderr}"
        )
    for line in proc.stdout.splitlines():
        if line.startswith("RESULT:"):
            return json.loads(line[len("RESULT:"):])
    raise RuntimeError(f"capture '{kind}' produced no RESULT line:\n{proc.stdout}")


def _capture_child(kind: str) -> None:
    """Entry point inside a capture subprocess: emit one RESULT JSON line."""
    # The subprocess is launched with cwd set to backend/ or mcp-server/; put it
    # first on sys.path so ``import server`` / ``import config`` resolve there
    # (Python adds the script dir, not the cwd, by default).
    sys.path.insert(0, os.getcwd())
    if kind == "discovery":
        result: object = _capture_discovery()
    elif kind == "as_flow":
        result = asyncio.run(_capture_as_flow())
    else:  # pragma: no cover - guarded by argparse-style dispatch
        raise SystemExit(f"unknown capture kind: {kind}")
    print("RESULT:" + json.dumps(result))


def main() -> None:
    # Each half runs in its own interpreter with the matching cwd so that
    # ``import config`` / ``import server`` resolve to the correct package.
    discovery = _run_capture_subprocess("discovery", cwd=MCP_DIR)
    as_steps = _run_capture_subprocess("as_flow", cwd=BACKEND_DIR)

    fixture = {
        "synthetic": True,
        "description": (
            "SYNTHETIC Claude Desktop OAuth-flow capture generated by driving the "
            "REAL ECM AS + MCP RS endpoints (no real Claude Desktop; the connector "
            "redirect_uri is still a placeholder — bead buiqr.6). Re-capture from a "
            "real connector flow once the redirect_uri is verified. See "
            "generate_oauth_flow_fixture.py for provenance."
        ),
        "generated_by": "mcp-server/tests/fixtures/generate_oauth_flow_fixture.py",
        "captured_against": {
            "as_endpoints": "backend/routers/oauth_mcp.py (real FastAPI app)",
            "rs_discovery": "mcp-server/server.py (real Starlette app)",
        },
        # Pinned so the replay test can verify the captured access token offline
        # (the mcp-server CI job cannot import the backend AS). TEST values only.
        "signing": {"secret": PINNED_SECRET, "issuer": PINNED_ISSUER, "audience": "ecm-mcp"},
        "flow": {
            "discovery": discovery,
            "steps": as_steps,
        },
    }
    FIXTURE_PATH.write_text(json.dumps(fixture, indent=2) + "\n")
    print(f"Wrote synthetic fixture: {FIXTURE_PATH}")


if __name__ == "__main__":
    if len(sys.argv) >= 3 and sys.argv[1] == "--capture":
        _capture_child(sys.argv[2])
    else:
        main()
