#!/usr/bin/env python3
"""Generate and verify the per-release SPDX 2.3 software bill of materials.

WHAT THIS DOCUMENT IS, AND WHAT IT IS NOT
-----------------------------------------
This is a **source-manifest** SBOM. It is derived from the dependency manifests
in the repository -- ``backend/requirements.txt``, ``frontend/package-lock.json``,
``mcp-server/requirements.txt`` -- and from the digest-pinned base images named
in the two Dockerfiles. It is **not** an image SBOM: it does not enumerate the
Debian or Alpine packages inside those base images, and it does not name an
image digest, because at release-cut time no release image exists yet.

That limitation is deliberate and load-bearing, so it is stated in the document
itself (``creationInfo.comment``) as well as here. An SBOM whose coverage is
misunderstood is worse than no SBOM, because it will be believed.

WHY NOT AN IMAGE SBOM (bead enhancedchannelmanager-3t0ht)
---------------------------------------------------------
An image SBOM has to be generated from an image, and the images a release
publishes are built *after* the release branch is frozen: ``build.yml`` runs on
the push to ``main`` that the release PR's merge commit creates. That merge
commit has a different SHA from the release branch tip, and ``Dockerfile`` bakes
``GIT_COMMIT`` into the ECM image as an ``ENV``, so the image built from the
release branch and the image published from ``main`` are guaranteed to have
different digests even though their contents are otherwise identical. Building
on ``release/**`` and inventorying *that* image would therefore commit a
document naming a digest that is not, and never will be, in the registry.

BINDING
-------
Because there is no image digest to bind to, this document binds to what it can
actually be checked against: the exact bytes of every manifest it was derived
from. ``sbom/vX.Y.Z/index.json`` records the SHA-256 of each source manifest,
and ``verify`` regenerates the documents from the working tree and byte-compares
them. Editing a requirement without regenerating, hand-editing a document, or
committing a document for the wrong version all fail the check. The only field
carried over from the committed document rather than recomputed is
``creationInfo.created``, which is a timestamp and cannot be re-derived; every
other byte is re-derived from the tree.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

SPDX_VERSION = "SPDX-2.3"
DATA_LICENSE = "CC0-1.0"
NOASSERTION = "NOASSERTION"
INDEX_SCHEMA = 1

# Namespaces are required by SPDX to be unique per document. Version plus
# document name is unique across this repository and, unlike a UUID, is
# reproducible -- which `verify` depends on.
NAMESPACE_ROOT = "https://github.com/motwakorb/enhancedchannelmanager/sbom"

PINNED_REQUIREMENT = re.compile(r"^(?P<name>[A-Za-z0-9][A-Za-z0-9._-]*)==(?P<version>[^\s;#]+)\s*$")
DOCKER_IMAGE_REF = re.compile(
    r"^(?P<image>[^\s@:]+(?::[^\s@]+)?)@(?P<digest>sha256:[0-9a-f]{64})$"
)
SPDX_ID_UNSAFE = re.compile(r"[^A-Za-z0-9.-]")

COVERAGE_INCLUDES = (
    "Python distributions pinned in the image's requirements.txt, with versions",
    "npm packages resolved in frontend/package-lock.json, with versions (ECM only)",
    "Base and build images referenced by digest in the Dockerfile",
)
COVERAGE_EXCLUDES = (
    "Operating-system packages inside the base images (apt/apk); the Dockerfiles "
    "also run `apt-get upgrade` / `apk upgrade` at build time, so the installed "
    "OS package set is not derivable from the source tree at all",
    "Transitive native libraries vendored inside Python wheels",
    "Any image digest: no release image exists when this document is cut",
)

CREATION_COMMENT = (
    "Source-manifest SBOM generated by scripts/generate_sbom.py from the "
    "repository's dependency manifests. It is NOT an image SBOM: the OS package "
    "set inside the digest-pinned base images is not enumerated, and no image "
    "digest is asserted. See sbom/README.md for the full coverage statement."
)


class SbomError(ValueError):
    """The tree, the arguments, or a committed document is unusable."""


def _spdx_id(*parts: str) -> str:
    return "SPDXRef-" + "-".join(SPDX_ID_UNSAFE.sub(".", part) for part in parts)


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        raise SbomError(f"cannot read {path}: {exc}") from exc


def _read_json(path: Path) -> Any:
    try:
        return json.loads(_read_text(path))
    except json.JSONDecodeError as exc:
        raise SbomError(f"{path} is not valid JSON: {exc.msg}") from exc


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    try:
        with path.open("rb") as handle:
            for chunk in iter(lambda: handle.read(1 << 20), b""):
                digest.update(chunk)
    except OSError as exc:
        raise SbomError(f"cannot hash {path}: {exc}") from exc
    return digest.hexdigest()


def parse_pinned_requirements(text: str, source: str) -> list[dict[str, str]]:
    """Return every ``name==version`` pin, rejecting anything unpinned.

    ``uv pip compile`` output is fully pinned by construction. A line that is
    not a pin means the manifest shape changed, and guessing at it would put a
    wrong version in a document people make patching decisions from -- so fail.
    """
    packages: list[dict[str, str]] = []
    for number, raw in enumerate(text.splitlines(), start=1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        match = PINNED_REQUIREMENT.fullmatch(line)
        if match is None:
            raise SbomError(f"{source} line {number} is not a simple pin: {line!r}")
        packages.append({"name": match["name"], "version": match["version"]})
    if not packages:
        raise SbomError(f"{source} declares no pinned requirements")
    return packages


def parse_lockfile_packages(document: Any, source: str) -> list[dict[str, Any]]:
    """Return every resolved npm package in an npm lockfile v2/v3 ``packages`` map."""
    if not isinstance(document, dict):
        raise SbomError(f"{source} is not a JSON object")
    if document.get("lockfileVersion") not in (2, 3):
        raise SbomError(
            f"{source} has unsupported lockfileVersion "
            f"{document.get('lockfileVersion')!r}; only v2/v3 are understood"
        )
    entries = document.get("packages")
    if not isinstance(entries, dict) or not entries:
        raise SbomError(f"{source} has no 'packages' map")
    packages: list[dict[str, Any]] = []
    for location, entry in entries.items():
        if location == "" or not isinstance(entry, dict):
            continue
        if entry.get("link") is True:
            continue
        marker = "node_modules/"
        if marker not in location:
            raise SbomError(f"{source} entry {location!r} is not a node_modules path")
        name = entry.get("name") or location[location.rindex(marker) + len(marker) :]
        version = entry.get("version")
        if not isinstance(name, str) or not isinstance(version, str) or not version:
            raise SbomError(f"{source} entry {location!r} has no resolved name/version")
        packages.append(
            {
                "name": name,
                "version": version,
                "dev": bool(entry.get("dev")),
                "license": entry.get("license") if isinstance(entry.get("license"), str) else None,
            }
        )
    if not packages:
        raise SbomError(f"{source} resolves no packages")
    return packages


def parse_dockerfile_images(text: str, source: str) -> list[dict[str, str]]:
    """Return every digest-pinned image the Dockerfile pulls, runtime last.

    Both ``FROM ref@sha256:...`` and ``COPY --from=ref@sha256:...`` are pulled
    into the build, so both belong in the inventory. An unpinned reference is
    rejected: an SBOM naming a floating tag records nothing verifiable.
    """
    images: dict[tuple[str, str], dict[str, str]] = {}
    stage_base: dict[str, tuple[str, str]] = {}
    runtime_key: tuple[str, str] | None = None

    def _record(entry: dict[str, str]) -> tuple[str, str]:
        key = (entry["image"], entry["digest"])
        images.setdefault(key, entry)
        return key

    for number, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        upper = line.upper()
        if upper.startswith("FROM "):
            tokens = line.split()[1:]
            if not tokens:
                raise SbomError(f"{source} line {number} has a bare FROM")
            reference = tokens[0]
            if reference in stage_base:
                key = stage_base[reference]
            else:
                key = _record(_pinned_image(reference, source, number, "base"))
            if len(tokens) >= 3 and tokens[1].upper() == "AS":
                stage_base[tokens[2]] = key
            runtime_key = key
        elif upper.startswith("COPY ") and "--from=" in line:
            reference = line.split("--from=", 1)[1].split()[0]
            if reference in stage_base:
                continue
            _record(_pinned_image(reference, source, number, "build"))
    if runtime_key is None:
        raise SbomError(f"{source} has no FROM instruction")
    # An image that is both an intermediate base and the final base is one
    # image; record it once, under the role that describes what ships.
    images[runtime_key]["role"] = "runtime"
    return [images[key] for key in sorted(images)]


def _pinned_image(reference: str, source: str, line: int, role: str) -> dict[str, str]:
    match = DOCKER_IMAGE_REF.fullmatch(reference)
    if match is None:
        raise SbomError(
            f"{source} line {line} references {reference!r} without a sha256 digest; "
            "an SBOM cannot record a floating image reference"
        )
    return {"image": match["image"], "digest": match["digest"], "role": role}


def _pypi_package(entry: dict[str, str]) -> dict[str, Any]:
    return {
        "SPDXID": _spdx_id("Package", "pypi", entry["name"], entry["version"]),
        "name": entry["name"],
        "versionInfo": entry["version"],
        "downloadLocation": NOASSERTION,
        "filesAnalyzed": False,
        "supplier": NOASSERTION,
        "licenseConcluded": NOASSERTION,
        "licenseDeclared": NOASSERTION,
        "copyrightText": NOASSERTION,
        "externalRefs": [
            {
                "referenceCategory": "PACKAGE-MANAGER",
                "referenceType": "purl",
                "referenceLocator": f"pkg:pypi/{entry['name']}@{entry['version']}",
            }
        ],
    }


def _npm_package(entry: dict[str, Any]) -> dict[str, Any]:
    declared = entry["license"] or NOASSERTION
    package = {
        "SPDXID": _spdx_id("Package", "npm", entry["name"], entry["version"]),
        "name": entry["name"],
        "versionInfo": entry["version"],
        "downloadLocation": NOASSERTION,
        "filesAnalyzed": False,
        "supplier": NOASSERTION,
        "licenseConcluded": NOASSERTION,
        "licenseDeclared": declared,
        "copyrightText": NOASSERTION,
        "externalRefs": [
            {
                "referenceCategory": "PACKAGE-MANAGER",
                "referenceType": "purl",
                "referenceLocator": f"pkg:npm/{entry['name']}@{entry['version']}",
            }
        ],
    }
    if entry["dev"]:
        package["comment"] = "Build-time only; not present in the published image."
    else:
        package["comment"] = (
            "node_modules is not copied into the published image; this package's "
            "code reaches the image only insofar as the bundler emitted it into "
            "/app/static."
        )
    return package


def _image_package(entry: dict[str, str]) -> dict[str, Any]:
    role = {
        "runtime": "Final base image of the published container.",
        "base": "Intermediate build-stage base image; not published.",
        "build": "Pulled during the build to copy a tool out of; not published.",
    }[entry["role"]]
    return {
        "SPDXID": _spdx_id("Package", "oci", entry["image"], entry["digest"][7:19]),
        "name": entry["image"],
        "versionInfo": entry["digest"],
        "downloadLocation": NOASSERTION,
        "filesAnalyzed": False,
        "supplier": NOASSERTION,
        "licenseConcluded": NOASSERTION,
        "licenseDeclared": NOASSERTION,
        "copyrightText": NOASSERTION,
        "checksums": [{"algorithm": "SHA256", "checksumValue": entry["digest"][7:]}],
        "comment": (
            f"{role} Its own OS package set is NOT enumerated by this document, "
            "and the Dockerfile applies OS security upgrades on top of it at "
            "build time."
        ),
        "externalRefs": [
            {
                "referenceCategory": "PACKAGE-MANAGER",
                "referenceType": "purl",
                "referenceLocator": f"pkg:oci/{entry['image'].rsplit('/', 1)[-1]}"
                f"?repository_url={entry['image']}&digest={entry['digest']}",
            }
        ],
    }


def _relationship(source: str, kind: str, target: str) -> dict[str, str]:
    return {
        "spdxElementId": source,
        "relationshipType": kind,
        "relatedSpdxElement": target,
    }


def build_document(
    *,
    subject: str,
    subject_name: str,
    version: str,
    created: str,
    pypi: list[dict[str, str]],
    npm: list[dict[str, Any]],
    images: list[dict[str, str]],
) -> dict[str, Any]:
    root_id = _spdx_id("Package", subject)
    packages: list[dict[str, Any]] = [
        {
            "SPDXID": root_id,
            "name": subject_name,
            "versionInfo": version,
            "downloadLocation": NOASSERTION,
            "filesAnalyzed": False,
            "supplier": NOASSERTION,
            "licenseConcluded": NOASSERTION,
            "licenseDeclared": NOASSERTION,
            "copyrightText": NOASSERTION,
            "primaryPackagePurpose": "CONTAINER",
        }
    ]
    relationships: list[dict[str, str]] = [
        _relationship("SPDXRef-DOCUMENT", "DESCRIBES", root_id)
    ]

    for entry in images:
        package = _image_package(entry)
        packages.append(package)
        kind = "CONTAINS" if entry["role"] == "runtime" else "BUILD_DEPENDENCY_OF"
        if kind == "CONTAINS":
            relationships.append(_relationship(root_id, "CONTAINS", package["SPDXID"]))
        else:
            relationships.append(_relationship(package["SPDXID"], kind, root_id))

    for entry in pypi:
        package = _pypi_package(entry)
        packages.append(package)
        relationships.append(
            _relationship(package["SPDXID"], "RUNTIME_DEPENDENCY_OF", root_id)
        )

    for entry in npm:
        package = _npm_package(entry)
        packages.append(package)
        kind = "DEV_DEPENDENCY_OF" if entry["dev"] else "BUILD_DEPENDENCY_OF"
        relationships.append(_relationship(package["SPDXID"], kind, root_id))

    packages[1:] = sorted(packages[1:], key=lambda item: item["SPDXID"])
    relationships[1:] = sorted(
        relationships[1:],
        key=lambda item: (item["relationshipType"], item["spdxElementId"]),
    )
    return {
        "spdxVersion": SPDX_VERSION,
        "dataLicense": DATA_LICENSE,
        "SPDXID": "SPDXRef-DOCUMENT",
        "name": f"{subject}-{version}",
        "documentNamespace": f"{NAMESPACE_ROOT}/v{version}/{subject}",
        "creationInfo": {
            "created": created,
            "creators": ["Tool: scripts/generate_sbom.py"],
            "comment": CREATION_COMMENT,
        },
        "documentDescribes": [root_id],
        "packages": packages,
        "relationships": relationships,
    }


SUBJECTS = {
    "ecm": {
        "subject_name": "enhanced-channel-manager",
        "dockerfile": "Dockerfile",
        "requirements": "backend/requirements.txt",
        "lockfile": "frontend/package-lock.json",
    },
    "mcp": {
        "subject_name": "enhanced-channel-manager-mcp",
        "dockerfile": "mcp-server/Dockerfile",
        "requirements": "mcp-server/requirements.txt",
        "lockfile": None,
    },
}


def read_version(root: Path) -> str:
    document = _read_json(root / "frontend" / "package.json")
    version = document.get("version") if isinstance(document, dict) else None
    if not isinstance(version, str) or not version:
        raise SbomError("frontend/package.json has no version string")
    return version


def render(root: Path, version: str, created: str) -> dict[str, Any]:
    """Return ``{relative path: serialized bytes}`` for the whole SBOM directory."""
    sources: dict[str, str] = {}
    documents: dict[str, dict[str, Any]] = {}

    for subject, spec in SUBJECTS.items():
        requirements_path = spec["requirements"]
        dockerfile_path = spec["dockerfile"]
        pypi = parse_pinned_requirements(
            _read_text(root / requirements_path), requirements_path
        )
        images = parse_dockerfile_images(_read_text(root / dockerfile_path), dockerfile_path)
        sources[requirements_path] = sha256_file(root / requirements_path)
        sources[dockerfile_path] = sha256_file(root / dockerfile_path)
        npm: list[dict[str, Any]] = []
        if spec["lockfile"]:
            npm = parse_lockfile_packages(
                _read_json(root / spec["lockfile"]), spec["lockfile"]
            )
            sources[spec["lockfile"]] = sha256_file(root / spec["lockfile"])
        documents[subject] = build_document(
            subject=subject,
            subject_name=spec["subject_name"],
            version=version,
            created=created,
            pypi=pypi,
            npm=npm,
            images=images,
        )

    rendered: dict[str, str] = {
        f"{subject}.spdx.json": _serialize(document)
        for subject, document in documents.items()
    }
    index = {
        "schema": INDEX_SCHEMA,
        "version": version,
        "created": created,
        "kind": "source-manifest",
        "subject": {
            "type": "source-tree",
            "note": (
                "These documents describe the dependency manifests of the release "
                "source tree. They do NOT describe a container image and assert no "
                "image digest; see sbom/README.md."
            ),
        },
        "coverage": {"includes": list(COVERAGE_INCLUDES), "excludes": list(COVERAGE_EXCLUDES)},
        "sources": {path: f"sha256:{digest}" for path, digest in sorted(sources.items())},
        "documents": [
            {
                "path": name,
                "subject": name.split(".", 1)[0],
                "packages": len(documents[name.split(".", 1)[0]]["packages"]),
                "sha256": hashlib.sha256(payload.encode("utf-8")).hexdigest(),
            }
            for name, payload in sorted(rendered.items())
        ],
    }
    rendered["index.json"] = _serialize(index)
    return rendered


def _serialize(document: Any) -> str:
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


def committed_created(directory: Path) -> str:
    """Return the ``created`` stamp of an already-committed SBOM directory.

    A timestamp cannot be re-derived from the tree, so ``verify`` reuses the
    committed one and re-derives every other byte. The stamp is therefore the
    one field this check does not police, which is stated rather than hidden.
    """
    index = _read_json(directory / "index.json")
    if not isinstance(index, dict):
        raise SbomError(f"{directory}/index.json is not a JSON object")
    created = index.get("created")
    if not isinstance(created, str) or not created:
        raise SbomError(f"{directory}/index.json has no 'created' stamp")
    return created


def audit(directory: Path) -> list[str]:
    """Return every internal inconsistency in a committed SBOM directory.

    This checks a document against its own index only, so it also applies to a
    *past* release whose source tree is no longer checked out. It catches the
    thing an archive is most likely to suffer: somebody hand-editing a document
    long after the release, leaving the index's recorded hash behind.
    """
    problems: list[str] = []
    index = _read_json(directory / "index.json")
    if not isinstance(index, dict):
        return [f"{directory.name}/index.json is not a JSON object"]
    if index.get("schema") != INDEX_SCHEMA:
        problems.append(f"{directory.name}/index.json schema is {index.get('schema')!r}")
    entries = index.get("documents")
    if not isinstance(entries, list) or not entries:
        return problems + [f"{directory.name}/index.json lists no documents"]
    listed = set()
    for entry in entries:
        if not isinstance(entry, dict) or not isinstance(entry.get("path"), str):
            problems.append(f"{directory.name}/index.json has a malformed document entry")
            continue
        name = entry["path"]
        listed.add(name)
        target = directory / name
        if not target.is_file():
            problems.append(f"{directory.name}/{name} is listed but missing")
            continue
        payload = _read_text(target)
        if hashlib.sha256(payload.encode("utf-8")).hexdigest() != entry.get("sha256"):
            problems.append(f"{directory.name}/{name} does not match its recorded sha256")
            continue
        document = json.loads(payload)
        if document.get("spdxVersion") != SPDX_VERSION:
            problems.append(f"{directory.name}/{name} is not {SPDX_VERSION}")
        if len(document.get("packages") or []) != entry.get("packages"):
            problems.append(f"{directory.name}/{name} package count differs from the index")
    present = {path.name for path in directory.iterdir() if path.is_file()}
    for name in sorted(present - listed - {"index.json"}):
        problems.append(f"{directory.name}/{name} is present but not listed in the index")
    return problems


def generate(root: Path, directory: Path, version: str, created: str) -> list[str]:
    rendered = render(root, version, created)
    directory.mkdir(parents=True, exist_ok=True)
    for name, payload in sorted(rendered.items()):
        (directory / name).write_text(payload, encoding="utf-8")
    return sorted(rendered)


def verify(root: Path, directory: Path, version: str) -> list[str]:
    """Return the list of drifted files; empty means the committed SBOM is current."""
    if not directory.is_dir():
        raise SbomError(
            f"no SBOM committed at {directory}; run "
            f"'python scripts/generate_sbom.py generate --version {version}'"
        )
    declared = read_version(root)
    if declared != version:
        raise SbomError(
            f"frontend/package.json is {declared} but the SBOM directory demands {version}"
        )
    rendered = render(root, version, committed_created(directory))
    present = {path.name for path in directory.iterdir() if path.is_file()}
    drifted = sorted(set(rendered) ^ present)
    for name, payload in sorted(rendered.items()):
        target = directory / name
        if not target.is_file():
            continue
        if _read_text(target) != payload and name not in drifted:
            drifted.append(name)
    return sorted(drifted)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Generate or verify the release SBOM.")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root (defaults to this script's parent).",
    )
    subparsers = parser.add_subparsers(dest="command", required=True)
    for name in ("generate", "verify", "audit"):
        sub = subparsers.add_parser(name)
        sub.add_argument(
            "--version",
            help="Release version; defaults to frontend/package.json.",
        )
        sub.add_argument(
            "--out",
            type=Path,
            help="SBOM directory; defaults to <repo-root>/sbom/v<version>.",
        )
        if name == "generate":
            sub.add_argument(
                "--created",
                help="SPDX creation timestamp; defaults to the current UTC time.",
            )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    root: Path = args.repo_root
    try:
        version = args.version or read_version(root)
        directory = args.out or root / "sbom" / f"v{version}"
        if args.command == "generate":
            created = args.created or datetime.now(timezone.utc).strftime(
                "%Y-%m-%dT%H:%M:%SZ"
            )
            for name in generate(root, directory, version, created):
                print(f"wrote {directory}/{name}")
            return 0
        if args.command == "audit":
            problems = audit(directory)
            if problems:
                print("SBOM FAIL: " + "; ".join(problems), file=sys.stderr)
                return 1
            print(f"SBOM PASS: {directory} is internally consistent")
            return 0
        drifted = verify(root, directory, version)
        if drifted:
            print(
                f"SBOM FAIL: {directory} does not match the source tree: "
                f"{', '.join(drifted)}",
                file=sys.stderr,
            )
            print(
                "Regenerate with "
                f"'python scripts/generate_sbom.py generate --version {version}' "
                "and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"SBOM PASS: {directory} matches the source tree")
        return 0
    except SbomError as exc:
        print(f"SBOM INPUT FAIL: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
